### ISSUE TITLE
the newest Flutter SDK is 1.2.1, but the package needs >=1.4.7  ?

### ISSUE THREAD

**Issue by sunshineinwater** [dannyvalente/flutter_selectable_text#1]
flutter_selectable_text >=0.2.0 which requires Flutter SDK version >=1.4.7 <2.0.0

**Comment by dannyvalente** [comment]
Flutter has 3 channels (other than the master channel): dev, beta and stable. Currently, the latest **stable** release is 1.2.1, but for those developing using the dev or beta channels need a version of this package that is compatible with those flutter SDK versions due to some changes that went into Flutter. The latest version of the Beta flutter SDK is actually 1.4.9.

See https://flutter.dev/docs/development/tools/sdk/releases?tab=linux
