### ISSUE TITLE
Missing attributes from the regular Text widget

### ISSUE THREAD

**Issue by IhorKlimov** [dannyvalente/flutter_selectable_text#2]
- strutStyle
- locale
- softWrap
- overflow
- textScaleFactor
- maxLines

**Comment by dannyvalente** [comment]
@IhorKlimov I apologize for the delay in responding. Because this widget is built using an underlying EditableText widget, then the only parameters it can support are the same as the TextField. Therefore, all of the above are not supported, except for *maxLines*. However, *maxLines* also has an issue where if it's set, the widget will actually lay itself out taking up all the space necessary for that number of lines, even if the Text supplied is shorter, so I decided to not support it.
